name: ZBrush SDK Docs Mirror
on:
  schedule:
    - cron: "0 12 * * 1"   # segundas 09:00 America/Sao_Paulo ≈ 12:00 UTC
  workflow_dispatch: {}

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Run scraper
        run: |
          python tools/zbrush_sdk_scrape.py

      - name: Commit changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "zbrush-mcp-bot"
            git config user.email "zbrush-mcp-bot@users.noreply.github.com"
            git add docs/zbrush-sdk
            git commit -m "docs(zbrush-sdk): update on $(date -u +'%Y-%m-%d')"
            git push
          else
            echo "Sem mudanças para comitar."
          fi
